# Scalars

A scalar is a single numerical value. It has no direction or dimension. In R, a scalar is simply a variable storing a number

In [1]:
scalar = 5
scalar

5

# Vectors

A vector is a one-dimensional array that contains numbers of the same type.

In [2]:
import numpy as np

vector = np.array([1, 2, 3, 4, 5])

In [3]:
vector

array([1, 2, 3, 4, 5])

In [4]:
vector[1]

np.int64(2)

# Matrices

A matrix is a 2D structure of numbers arranged in rows and columns.

In [5]:
matrix_2x3 = np.array([[1, 3, 5], [2, 4, 6]])
matrix_2x3

array([[1, 3, 5],
       [2, 4, 6]])

# Tensors

A tensor is a generalization of matrices to higher dimensions. In Python, we use NumPy arrays to represent tensors.

In [10]:
tensor = np.arange(1, 25).reshape(2, 3, 4)  # 2 rows, 3 columns, 4 layers
tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])