# Scalars

A scalar is a single numerical value. It has no direction or dimension. In R, a scalar is simply a variable storing a number

In [1]:
scalar = 5
scalar

5

# Vectors

A vector is a one-dimensional array that contains numbers of the same type.

In [2]:
import numpy as np

vector = np.array([1, 2, 3, 4, 5])

In [3]:
vector

array([1, 2, 3, 4, 5])

In [4]:
vector[1]

np.int64(2)

# Matrices

A matrix is a 2D structure of numbers arranged in rows and columns.

In [5]:
matrix_2x3 = np.array([[1, 3, 5], [2, 4, 6]])
matrix_2x3

array([[1, 3, 5],
       [2, 4, 6]])

# Tensors

A tensor is a generalization of matrices to higher dimensions. In Python, we use NumPy arrays to represent tensors.

In [10]:
tensor = np.arange(1, 25).reshape(2, 3, 4)  # 2 rows, 3 columns, 4 layers
tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

## Vector and Matrix Notation

* Row Vector

A row vector is a 1×n matrix (1 row, multiple columns)

In [11]:
row_vector = np.array([[1, 2, 3]])
row_vector

array([[1, 2, 3]])

* Column Vector

A column vector is an n×1 matrix (multiple rows, 1 column).

In [12]:
column_vector = np.array([[1], [2], [3]])
column_vector


array([[1],
       [2],
       [3]])

# Types of Matrices

* Square Matrix

A square matrix has the same number of rows and columns.

In [13]:
square_matrix = np.array([[1, 2], [3, 4]])
square_matrix


array([[1, 2],
       [3, 4]])

* Diagonal Matrix

A diagonal matrix has non-zero values only on the diagonal.

In [14]:
diagonal_matrix = np.diag([1, 2, 3])
diagonal_matrix

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

* Zero Matrix

A zero matrix has all elements equal to 0.

In [15]:
zero_matrix = np.zeros((3, 3))
zero_matrix


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# Matrix Operations

* Matrix Addition

To add two matrices, they must have the same dimensions.

In [16]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = A + B

In [17]:
C

array([[ 6,  8],
       [10, 12]])

* Matrix Subtraction

Similar to addition, we subtract matrices element-wise.

In [18]:
D = A - B
D


array([[-4, -4],
       [-4, -4]])

# Matrix Multiplication

Element-wise Multiplication (Hadamard Product)

In [19]:
E = A * B

In [20]:
E

array([[ 5, 12],
       [21, 32]])

* Dot Product (Matrix Multiplication)

Use @ or np.dot() for proper matrix multiplication.

In [21]:
F = A @ B
F

array([[19, 22],
       [43, 50]])