# Matrix Multiplication (Row-by-Column)

In [1]:
import numpy as np

In [2]:
# Define a square matrix A
A = np.array([[1, 2], 
              [3, 4]])

# Define another matrix B
B = np.array([[5, 6], 
              [7, 8]])

In [3]:
result = np.dot(A, B)  # or A @ B

In [6]:
result

array([[19, 22],
       [43, 50]])

In [4]:
result =  A @ B

In [5]:
result

array([[19, 22],
       [43, 50]])

# Transpose of a Matrix

In [7]:
transpose_A = A.T

In [8]:
transpose_A

array([[1, 3],
       [2, 4]])

In [9]:
transpose_A = np.transpose(A)

In [10]:
transpose_A

array([[1, 3],
       [2, 4]])