In [1]:
import numpy as np
from scipy.sparse import csr_matrix

# 1. ORTHOGONAL MATRICES

In [2]:
# A matrix Q is orthogonal if Q.T * Q = I (Identity matrix)
Q = np.array([[0, -1], [1, 0]])  # A simple 2D rotation matrix

In [3]:
Q

array([[ 0, -1],
       [ 1,  0]])

In [4]:
is_orthogonal = np.allclose(Q.T @ Q, np.eye(2))

In [5]:
is_orthogonal

True

In [6]:
Q.T @ Q

array([[1, 0],
       [0, 1]])

# 2. SYMMETRIC AND SKEW-SYMMETRIC MATRICES

In [7]:
# Symmetric Matrix: A matrix is symmetric if A.T = A
A_symmetric = np.array([[2, 3], [3, 4]])  # A.T should be equal to A

In [8]:
A_symmetric

array([[2, 3],
       [3, 4]])

In [9]:
A_symmetric.T

array([[2, 3],
       [3, 4]])

In [10]:
# Skew-Symmetric Matrix: A matrix is skew-symmetric if A.T = -A
A_skew = np.array([[0, -2], [2, 0]])  # A.T should be -A

In [11]:
A_skew

array([[ 0, -2],
       [ 2,  0]])

In [12]:
A_skew.T

array([[ 0,  2],
       [-2,  0]])

In [13]:
np.allclose(A_skew, -A_skew.T)

True

# 3. POSITIVE DEFINITE MATRICES

In [14]:
# A matrix A is positive definite if all its eigenvalues are positive
A_pos_def = np.array([[2, -1], [-1, 2]])  # A symmetric matrix with positive eigenvalues

In [15]:
eigenvalues = np.linalg.eigvals(A_pos_def)

In [16]:
is_positive_definite = np.all(eigenvalues > 0)

In [17]:
is_positive_definite

np.True_

# 4. SPARSE MATRICES

In [18]:
# A sparse matrix is a matrix that has a large number of zero elements
dense_matrix = np.array([[0, 0, 3], [4, 0, 0], [0, 5, 0]])  # A dense representation

In [19]:
dense_matrix

array([[0, 0, 3],
       [4, 0, 0],
       [0, 5, 0]])

In [20]:
# Convert to sparse format (Compressed Sparse Row)
sparse_matrix = csr_matrix(dense_matrix)

In [21]:
sparse_matrix

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3 stored elements and shape (3, 3)>

In [22]:
sparse_matrix.data

array([3, 4, 5])