In [ ]:
"""
Singular Value Decomposition (SVD), Low-Rank Approximation, and Principal Component Analysis (PCA)

1. Singular Value Decomposition (SVD)

Definition:
SVD is a factorization of a real or complex matrix. For a matrix A of size m x n, SVD decomposes it into three matrices:
    A = U Σ V^T
    - U: An m x m orthogonal matrix (left singular vectors).
    - Σ: An m x n diagonal matrix with non-negative real numbers on the diagonal (singular values).
    - V^T: An n x n orthogonal matrix (right singular vectors).

"""

In [1]:
import numpy as np

In [2]:
# Example matrix
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [3]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
# Perform SVD
U, S, VT = np.linalg.svd(A)

In [6]:
U

array([[-0.21483724,  0.88723069,  0.40824829],
       [-0.52058739,  0.24964395, -0.81649658],
       [-0.82633754, -0.38794278,  0.40824829]])

In [7]:
S

array([1.68481034e+01, 1.06836951e+00, 4.41842475e-16])

In [8]:
VT

array([[-0.47967118, -0.57236779, -0.66506441],
       [-0.77669099, -0.07568647,  0.62531805],
       [-0.40824829,  0.81649658, -0.40824829]])