In [1]:
import numpy as np
from scipy.linalg import lu, solve

# 1. SOLVING LINEAR SYSTEMS

In [2]:
# Example system: 
# 2x + y - z = 8
# -3x - y + 2z = -11
# -2x + y + 2z = -3

In [3]:

A = np.array([[2, 1, -1], [-3, -1, 2], [-2, 1, 2]])  # Coefficient matrix
b = np.array([8, -11, -3])  # Constant terms

In [4]:
A

array([[ 2,  1, -1],
       [-3, -1,  2],
       [-2,  1,  2]])

In [5]:
b

array([  8, -11,  -3])

In [6]:
# Solution using Gaussian Elimination (numpy.linalg.solve)
x = np.linalg.solve(A, b)

In [7]:
x

array([ 2.,  3., -1.])