#  Vector Addition and Subtraction

In [18]:
# Addition: The sum of two vectors is obtained by adding their corresponding components.
# Subtraction: The difference of two vectors is obtained by subtracting their corresponding components.

In [19]:
a = [1, 2, 3]  # Example vector a
b = [4, 5, 6]  # Example vector b

3-element Vector{Int64}:
 4
 5
 6

In [20]:
# Vector addition
addition_result = a .+ b

3-element Vector{Int64}:
 5
 7
 9

In [21]:
# In Julia, the dot (.) before an operator (e.g., .+, .-, .*, ./) is used for element-wise operations (also called broadcasting).

In [22]:
# Vector subtraction
subtraction_result = a .- b
subtraction_result

3-element Vector{Int64}:
 -3
 -3
 -3

# Scalar Multiplication

In [23]:
# Scalar multiplication: Multiply each component of the vector by a scalar (a real number).

In [24]:
scalar = 3  # Example scalar value

# Scalar multiplication of vector a
scalar_multiplication_result = scalar .* a
scalar_multiplication_result

3-element Vector{Int64}:
 3
 6
 9

# Dot Product

In [25]:
# The dot product of two vectors is the sum of the products of their corresponding components.
# a · b = a1 * b1 + a2 * b2 + a3 * b3 + ...

In [26]:
using LinearAlgebra

# Dot product of a and b
dot_product_result = dot(a, b)
dot_product_result

32

In [27]:
dot_product_result = sum(a .* b)

32

# Cross Product

In [28]:
# The cross product of two vectors results in a new vector that is perpendicular to both input vectors.
# a × b = (a2*b3 - a3*b2, a3*b1 - a1*b3, a1*b2 - a2*b1)

In [29]:
# Cross product of a and b
cross_product_result = cross(a, b)


3-element Vector{Int64}:
 -3
  6
 -3

In [30]:
# Define vectors a and b
a = [1, 2, 3]
b = [4, 5, 6]

# Initialize the result vector for the cross product
cross_product_result = zeros(3)

# Compute the cross product using a loop
for i in 1:3
    if i == 1
        cross_product_result[i] = a[2] * b[3] - a[3] * b[2]
    elseif i == 2
        cross_product_result[i] = a[3] * b[1] - a[1] * b[3]
    elseif i == 3
        cross_product_result[i] = a[1] * b[2] - a[2] * b[1]
    end
end
cross_product_result

3-element Vector{Float64}:
 -3.0
  6.0
 -3.0

# Norms and Distance Metrics (L1, L2 Norms)

In [32]:
# L1 Norm
l1_norm = sum(abs.(a))
l1_norm

6

In [33]:
# L2 Norm
l2_norm = norm(a)
l2_norm

3.7416573867739413