### Eigenvalue Decomposition (EVD)

Eigenvalue decomposition factorizes a matrix **A** into:

\[
A = V \Lambda V^{-1}
\]

where:

- **V** is the matrix of eigenvectors.
- **Λ** is the diagonal matrix of eigenvalues.

In [ ]:
# Define a square matrix
A <- matrix(c(4, -2, 1, -2, 3, -1, 1, -1, 2), nrow=3, byrow=TRUE)

LoadError: UndefVarError: `A` not defined in `Main`
Suggestion: check for spelling errors or missing imports.

In [ ]:
A

[,1] [,2] [,3]
[1,]  4   -2    1  
[2,] -2    3   -1  
[3,]  1   -1    2

In [ ]:
eigen_result <- eigen(A)

In [ ]:
eigen_result

eigen() decomposition
$values
[1] 6.048917 1.643104 1.307979

$vectors
           [,1]       [,2]      [,3]
[1,]  0.7369762 -0.5910090 0.3279853
[2,] -0.5910090 -0.3279853 0.7369762
[3,]  0.3279853  0.7369762 0.5910090


In [ ]:
eigen_result$values

[1] 6.048917 1.643104 1.307979

In [ ]:
eigen_result$vectors

[,1]       [,2]       [,3]     
[1,]  0.7369762 -0.5910090 0.3279853
[2,] -0.5910090 -0.3279853 0.7369762
[3,]  0.3279853  0.7369762 0.5910090

In [ ]:
# Verify decomposition: A * V = V * Lambda
V <- eigen_result$vectors
Lambda <- diag(eigen_result$values)
A_reconstructed <- V %*% Lambda %*% solve(V)

In [ ]:
A_reconstructed

[,1] [,2] [,3]
[1,]  4   -2    1  
[2,] -2    3   -1  
[3,]  1   -1    2