The **Spectral Theorem** states that any symmetric matrix \( A \) can be decomposed as:  

\[
A = Q Λ Q^T
\]

where:  

- \( Q \) is an **orthogonal matrix** of eigenvectors (\( Q^T Q = I \)).  
- \( Λ) is a **diagonal matrix** of eigenvalues.  


In [2]:
# Define a symmetric matrix
A_sym <- matrix(c(2, -1, 0, -1, 2, -1, 0, -1, 2), nrow=3, byrow=TRUE)

In [3]:
A_sym

[,1] [,2] [,3]
[1,]  2   -1    0  
[2,] -1    2   -1  
[3,]  0   -1    2

In [5]:
# Compute eigenvalues and eigenvectors
eigen_sym <- eigen(A_sym)

In [6]:
eigen_sym

eigen() decomposition
$values
[1] 3.4142136 2.0000000 0.5857864

$vectors
           [,1]          [,2]      [,3]
[1,] -0.5000000 -7.071068e-01 0.5000000
[2,]  0.7071068  1.099065e-15 0.7071068
[3,] -0.5000000  7.071068e-01 0.5000000


In [7]:
# Verify the spectral theorem
Q <- eigen_sym$vectors
Lambda <- diag(eigen_sym$values)

In [8]:
Q

[,1]       [,2]          [,3]     
[1,] -0.5000000 -7.071068e-01 0.5000000
[2,]  0.7071068  1.099065e-15 0.7071068
[3,] -0.5000000  7.071068e-01 0.5000000

In [13]:
Lambda

[,1]     [,2] [,3]     
[1,] 3.414214 0    0.0000000
[2,] 0.000000 2    0.0000000
[3,] 0.000000 0    0.5857864

In [14]:
# Reconstruction of the matrix
A_reconstructed_sym <- Q %*% Lambda %*% t(Q)

In [15]:
A_reconstructed_sym

[,1]          [,2] [,3]         
[1,]  2.000000e+00 -1   -3.711637e-16
[2,] -1.000000e+00  2   -1.000000e+00
[3,] -3.504812e-16 -1    2.000000e+00